# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-08 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordatainterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementresult',
            options={'managed': False},
        ),
    ]
