# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-20 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordatainterface', '0002_auto_20170329_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementresult',
            options={},
        ),
    ]
